



insert into `udip_otter`.`check_data_info` ( `CHECK_END_DATE`, `CHECK_TARGET_TABLE`, `CHECK_SOURCE_SCHEMA`, `UPDATE_DATE`, `REPAIR_FAIL_NUM`, `PIPELINE_ID`, `CHECK_SOURCE_TABLE`, `CHECK_SOURCE_NAME`, `CHANNEL_ID`, `CHECK_TARGET_NAME`, `CREATE_DATE`, `CHECK_TARGET_SCHEMA`, `IS_START`, `CHECK_BEGIN_DATE`) values ( null, 'department', 'xxgl', '2018-09-28 21:19:26', '0', '1', 'tb_department', '悦享读-xxgl', '1', 'target', '2018-09-28 21:19:26', 'udip_otter', '1', null);
insert into `udip_otter`.`check_data_info` ( `CHECK_END_DATE`, `CHECK_TARGET_TABLE`, `CHECK_SOURCE_SCHEMA`, `UPDATE_DATE`, `REPAIR_FAIL_NUM`, `PIPELINE_ID`, `CHECK_SOURCE_TABLE`, `CHECK_SOURCE_NAME`, `CHANNEL_ID`, `CHECK_TARGET_NAME`, `CREATE_DATE`, `CHECK_TARGET_SCHEMA`, `IS_START`, `CHECK_BEGIN_DATE`) values ( null, 'system_param', 'xxgl', '2018-09-29 11:13:53', '0', '1', 'tb_system_param', '悦享读-xxgl', '1', 'target', '2018-09-28 21:19:26', 'udip_otter', '1', null);
insert into `udip_otter`.`check_data_info` ( `CHECK_END_DATE`, `CHECK_TARGET_TABLE`, `CHECK_SOURCE_SCHEMA`, `UPDATE_DATE`, `REPAIR_FAIL_NUM`, `PIPELINE_ID`, `CHECK_SOURCE_TABLE`, `CHECK_SOURCE_NAME`, `CHANNEL_ID`, `CHECK_TARGET_NAME`, `CREATE_DATE`, `CHECK_TARGET_SCHEMA`, `IS_START`, `CHECK_BEGIN_DATE`) values ( null, 'classtime_type', 'xxgl', '2018-09-29 11:13:54', '0', '1', 'tb_classtime_type', '悦享读-xxgl', '1', 'target', '2018-09-28 21:19:26', 'udip_otter', '1', null);
insert into `udip_otter`.`check_data_info` ( `CHECK_END_DATE`, `CHECK_TARGET_TABLE`, `CHECK_SOURCE_SCHEMA`, `UPDATE_DATE`, `REPAIR_FAIL_NUM`, `PIPELINE_ID`, `CHECK_SOURCE_TABLE`, `CHECK_SOURCE_NAME`, `CHANNEL_ID`, `CHECK_TARGET_NAME`, `CREATE_DATE`, `CHECK_TARGET_SCHEMA`, `IS_START`, `CHECK_BEGIN_DATE`) values ( null, 'clazz', 'xxgl', '2018-09-29 11:13:55', '0', '1', 'tb_class', '悦享读-xxgl', '1', 'target', '2018-09-28 21:19:26', 'udip_otter', '1', null);
insert into `udip_otter`.`check_data_info` ( `CHECK_END_DATE`, `CHECK_TARGET_TABLE`, `CHECK_SOURCE_SCHEMA`, `UPDATE_DATE`, `REPAIR_FAIL_NUM`, `PIPELINE_ID`, `CHECK_SOURCE_TABLE`, `CHECK_SOURCE_NAME`, `CHANNEL_ID`, `CHECK_TARGET_NAME`, `CREATE_DATE`, `CHECK_TARGET_SCHEMA`, `IS_START`, `CHECK_BEGIN_DATE`) values ( null, 'curriculum', 'xxgl', '2018-09-28 21:19:26', '0', '1', 'tb_curriculum', '悦享读-xxgl', '1', 'target', '2018-09-28 21:19:26', 'udip_otter', '1', null);
insert into `udip_otter`.`check_data_info` ( `CHECK_END_DATE`, `CHECK_TARGET_TABLE`, `CHECK_SOURCE_SCHEMA`, `UPDATE_DATE`, `REPAIR_FAIL_NUM`, `PIPELINE_ID`, `CHECK_SOURCE_TABLE`, `CHECK_SOURCE_NAME`, `CHANNEL_ID`, `CHECK_TARGET_NAME`, `CREATE_DATE`, `CHECK_TARGET_SCHEMA`, `IS_START`, `CHECK_BEGIN_DATE`) values ( null, 'classtime', 'xxgl', '2018-09-28 21:19:26', '0', '1', 'tb_classtime', '悦享读-xxgl', '1', 'target', '2018-09-28 21:19:26', 'udip_otter', '1', null);
insert into `udip_otter`.`check_data_info` ( `CHECK_END_DATE`, `CHECK_TARGET_TABLE`, `CHECK_SOURCE_SCHEMA`, `UPDATE_DATE`, `REPAIR_FAIL_NUM`, `PIPELINE_ID`, `CHECK_SOURCE_TABLE`, `CHECK_SOURCE_NAME`, `CHANNEL_ID`, `CHECK_TARGET_NAME`, `CREATE_DATE`, `CHECK_TARGET_SCHEMA`, `IS_START`, `CHECK_BEGIN_DATE`) values ( null, 'classlevel', 'xxgl', '2018-09-28 21:19:26', '0', '1', 'tb_classlevel', '悦享读-xxgl', '1', 'target', '2018-09-28 21:19:26', 'udip_otter', '1', null);
insert into `udip_otter`.`check_data_info` ( `CHECK_END_DATE`, `CHECK_TARGET_TABLE`, `CHECK_SOURCE_SCHEMA`, `UPDATE_DATE`, `REPAIR_FAIL_NUM`, `PIPELINE_ID`, `CHECK_SOURCE_TABLE`, `CHECK_SOURCE_NAME`, `CHANNEL_ID`, `CHECK_TARGET_NAME`, `CREATE_DATE`, `CHECK_TARGET_SCHEMA`, `IS_START`, `CHECK_BEGIN_DATE`) values ( null, 'change_course_amount', 'xxgl', '2018-09-28 21:19:26', '0', '1', 'tb_change_course_amount', '悦享读-xxgl', '1', 'target', '2018-09-28 21:19:26', 'udip_otter', '1', null);
insert into `udip_otter`.`check_data_info` ( `CHECK_END_DATE`, `CHECK_TARGET_TABLE`, `CHECK_SOURCE_SCHEMA`, `UPDATE_DATE`, `REPAIR_FAIL_NUM`, `PIPELINE_ID`, `CHECK_SOURCE_TABLE`, `CHECK_SOURCE_NAME`, `CHANNEL_ID`, `CHECK_TARGET_NAME`, `CREATE_DATE`, `CHECK_TARGET_SCHEMA`, `IS_START`, `CHECK_BEGIN_DATE`) values ( null, 'class_regist_count', 'xxgl', '2018-09-28 21:19:26', '0', '1', 'tb_class_regist_count', '悦享读-xxgl', '1', 'target', '2018-09-28 21:19:26', 'udip_otter', '1', null);
insert into `udip_otter`.`check_data_info` ( `CHECK_END_DATE`, `CHECK_TARGET_TABLE`, `CHECK_SOURCE_SCHEMA`, `UPDATE_DATE`, `REPAIR_FAIL_NUM`, `PIPELINE_ID`, `CHECK_SOURCE_TABLE`, `CHECK_SOURCE_NAME`, `CHANNEL_ID`, `CHECK_TARGET_NAME`, `CREATE_DATE`, `CHECK_TARGET_SCHEMA`, `IS_START`, `CHECK_BEGIN_DATE`) values ( null, 'district', 'xxgl', '2018-09-28 21:19:27', '0', '1', 'tb_district', '悦享读-xxgl', '1', 'target', '2018-09-28 21:19:27', 'udip_otter', '1', null);


insert into  `udip_otter`.`check_data_info` ( `CHECK_END_DATE`, `CHECK_TARGET_TABLE`, `CHECK_SOURCE_SCHEMA`, `UPDATE_DATE`, `REPAIR_FAIL_NUM`, `PIPELINE_ID`, `CHECK_SOURCE_TABLE`, `CHECK_SOURCE_NAME`, `CHANNEL_ID`, `CHECK_TARGET_NAME`, `CREATE_DATE`, `CHECK_TARGET_SCHEMA`, `IS_START`, `CHECK_BEGIN_DATE`) values ( null, 'department', 'xxgl', '2018-09-27 11:00:06', '0', '1', 'tb_department', '悦享读-xxgl', '1', 'target', '2018-09-27 10:44:34', 'udip_otter', '1', null);
insert into  `udip_otter`.`check_data_info` ( `CHECK_END_DATE`, `CHECK_TARGET_TABLE`, `CHECK_SOURCE_SCHEMA`, `UPDATE_DATE`, `REPAIR_FAIL_NUM`, `PIPELINE_ID`, `CHECK_SOURCE_TABLE`, `CHECK_SOURCE_NAME`, `CHANNEL_ID`, `CHECK_TARGET_NAME`, `CREATE_DATE`, `CHECK_TARGET_SCHEMA`, `IS_START`, `CHECK_BEGIN_DATE`) values ( null, 'system_param', 'xxgl', '2018-09-27 11:00:06', '0', '1', 'tb_system_param', '悦享读-xxgl', '1', 'target', '2018-09-27 10:44:34', 'udip_otter', '1', null);

