

DROP TABLE IF EXISTS `clase`;
CREATE TABLE `clase` (
  `id` varchar(32) NOT NULL COMMENT '主键ID 32位',
  `city_id` varchar(10) NOT NULL COMMENT '城市编码',
  `class_id` varchar(32) NOT NULL COMMENT '班级ID',
  `stages_num` int(3) NOT NULL COMMENT '分期号，从1开始',
  `stages_count` int(3) NOT NULL COMMENT '总期数 最小为1',
  `stages_name` varchar(50) NOT NULL COMMENT '分期名称',
  `curriculum_count` int(3) NOT NULL COMMENT '当期课次总数',
  `start_curriculum_num` int(3) NOT NULL COMMENT '开始课次号',
  `end_curriculum_num` int(3) NOT NULL COMMENT '结束课次号',
  `start_curriculum_time` datetime NOT NULL COMMENT '开始课次时间',
  `end_curriculum_time` datetime NOT NULL COMMENT '结束课次时间',
  `start_payment_time` datetime DEFAULT NULL COMMENT '支付开始时间',
  `end_payment_time` datetime DEFAULT NULL COMMENT '支付结束时间',
  `status` int(1) DEFAULT '0' COMMENT '当期状态（0：未开始，1：进行中，2：已结束，默认：0）',
  `is_delete` int(1) DEFAULT '0' COMMENT '是否删除（0：正常，1：已删除，默认：0）',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `is_date_limit` int(1) DEFAULT '0' COMMENT '是否超出政策范围（0：正常，1：超出，默认：0）',
  `price` double DEFAULT '0' COMMENT '每期金额',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `rgse`;
CREATE TABLE `rgse` (
  `id` varchar(32) NOT NULL COMMENT '主键',
  `city_id` varchar(10) NOT NULL COMMENT '城市编码',
  `regist_id` varchar(32) NOT NULL COMMENT '报名id',
  `student_id` varchar(32) NOT NULL COMMENT '学员id',
  `student_uid` varchar(32) NOT NULL COMMENT '学员uid',
  `class_id` varchar(32) NOT NULL COMMENT '班级id',
  `class_stage_id` varchar(32) NOT NULL COMMENT '班级分期ID',
  `stages_num` int(3) NOT NULL DEFAULT '1' COMMENT '分期号，从1开始',
  `payed` int(1) NOT NULL DEFAULT '0' COMMENT '是否已缴费,0:未缴费,1:已缴费',
  `curriculum_count` int(3) NOT NULL DEFAULT '0' COMMENT '分期内剩余课次数',
  `add_curriculum_count` int(2) NOT NULL DEFAULT '0' COMMENT '补课课次',
  `auto_cancel` int(1) NOT NULL DEFAULT '0' COMMENT '是否需要自动删除,0:不需要,1:需要',
  `deleted` int(1) NOT NULL DEFAULT '0' COMMENT '是否已删除,0:未删除,1:已删除',
  `deleted_sign` varchar(32) NOT NULL DEFAULT '000000' COMMENT '删除标记:未删除:000000,已删除为id',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `modify_time` datetime DEFAULT NULL COMMENT '修改时间',
  `pay_time` datetime DEFAULT NULL COMMENT '支付时间',
  `cancel_time` datetime DEFAULT NULL COMMENT '退费或者撤单时间',
  `deleted_time` datetime DEFAULT NULL COMMENT '删除时间',
  `remark` varchar(100) DEFAULT NULL COMMENT '备注',
  `org_code` varchar(32) NOT NULL COMMENT '所在分校',
  `tm_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '时间戳',
  `is_continue` int(3) NOT NULL DEFAULT '0' COMMENT '报名类型(0：正常报名；1：续报；2：跨班报；3：候补报名；4：预报名；)',
  `source_class_id` varchar(32) DEFAULT NULL COMMENT '续报原班id',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='购课单表';

 
DROP TABLE IF EXISTS `rg`;
CREATE TABLE `rg` (
  `id` varchar(32) NOT NULL,
  `city_id` varchar(10) NOT NULL COMMENT '城市编码',
  `class_id` varchar(32) DEFAULT NULL,
  `iscontinue` int(11) DEFAULT NULL,
  `isdeleted` int(11) DEFAULT '0',
  `student_id` varchar(32) DEFAULT NULL,
  `ispay` int(11) DEFAULT '0',
  `way` int(11) DEFAULT NULL,
  `class_no` int(11) DEFAULT NULL,
  `add_class_quantity` int(11) DEFAULT '0',
  `is_all_course` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否是全价课（0：否；1：是）',
  `pay_enddate` datetime DEFAULT NULL,
  `source_class_id` varchar(32) DEFAULT NULL,
  `is_test` int(11) DEFAULT '0',
  `is_statistic` int(11) NOT NULL DEFAULT '1',
  `listener_code` varchar(100) DEFAULT NULL,
  `listenercard_id` varchar(32) DEFAULT NULL,
  `create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_id` varchar(32) DEFAULT NULL,
  `remark` varchar(800) DEFAULT NULL,
  `version` int(11) DEFAULT '0',
  `is_newstu` int(11) NOT NULL DEFAULT '0',
  `passedcount` int(11) NOT NULL DEFAULT '0',
  `isbankpay` int(10) DEFAULT '0',
  `reserved_times` int(11) NOT NULL DEFAULT '0' COMMENT '记录预留转班次数',
  `is_reserved` int(11) NOT NULL DEFAULT '0' COMMENT '是否预留转班（0否，1是）',
  `reserve_source_class_id` varchar(32) DEFAULT NULL COMMENT '预转班源班级ID',
  `reserved_change_classes_deadline` datetime DEFAULT NULL,
  `is_receipt_books` int(2) DEFAULT '0' COMMENT '是否领取书0:未领取1:领取',
  `modify_id` varchar(32) DEFAULT NULL COMMENT '修改人id',
  `modify_date` timestamp NULL DEFAULT NULL COMMENT '修改日期',
  `bi_test` int(11) DEFAULT '0' COMMENT '是否为测试数据0：否；1：是',
  `pay_date` datetime DEFAULT NULL,
  `candidate_no` varchar(12) DEFAULT NULL,
  `candidate_serviceCenter_id` varchar(32) DEFAULT NULL,
  `seat` int(11) DEFAULT NULL,
  `is_send_sms` int(11) DEFAULT '0',
  `beili_course_id` varchar(32) DEFAULT NULL COMMENT '在线外教排课id',
  `is_beili_course_no` int(11) DEFAULT '0' COMMENT '是否选课',
  `crm_statistic` int(11) NOT NULL DEFAULT '0',
  `activity` varchar(255) DEFAULT NULL COMMENT '报名渠道-活动名称',
  `associated_common_class_type` int(10) DEFAULT NULL COMMENT '限制方式 0:强制 1:推荐 2:无限制',
  `associated_common_class_id` varchar(32) DEFAULT NULL COMMENT '配对的普通班报名ID',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;




DROP TABLE IF EXISTS `stu`;
CREATE TABLE `stu` (
  `id` varchar(32) NOT NULL DEFAULT '',
  `city_id` varchar(10) NOT NULL COMMENT '城市编码',
  `loginname` varchar(20) DEFAULT NULL,
  `uid` int(11) DEFAULT NULL,
  `loginpwd` varchar(32) DEFAULT NULL,
  `if_paidregfee` int(11) DEFAULT '0',
  `is_modify` int(11) NOT NULL DEFAULT '0',
  `name` varchar(30) DEFAULT NULL,
  `real_name` varchar(30) DEFAULT NULL,
  `sex` int(11) DEFAULT '0',
  `loginemail` varchar(30) DEFAULT NULL,
  `birthday` date DEFAULT NULL,
  `grade_type` int(11) DEFAULT '0',
  `school_census` char(20) DEFAULT NULL,
  `grade_id` varchar(32) DEFAULT NULL,
  `grade_order` varchar(10) DEFAULT NULL,
  `address` varchar(100) DEFAULT NULL,
  `post` varchar(10) DEFAULT NULL,
  `father_name` varchar(20) DEFAULT NULL,
  `father_tel` varchar(20) DEFAULT NULL,
  `father_message_type` int(11) DEFAULT '0',
  `father_dept_tel` varchar(20) DEFAULT NULL,
  `father_identify_num` varchar(20) DEFAULT NULL,
  `father_identify_type` int(11) DEFAULT '0',
  `mater_name` varchar(20) DEFAULT NULL,
  `mater_tel` varchar(20) DEFAULT NULL,
  `mater_message_type` int(11) DEFAULT '0',
  `mater_dept_tel` varchar(20) DEFAULT NULL,
  `mater_Identify_num` varchar(20) DEFAULT NULL,
  `mater_identify_type` int(11) DEFAULT '0',
  `receive_email_type` int(11) DEFAULT '0',
  `phone` varchar(20) DEFAULT NULL,
  `identify_num` varchar(20) DEFAULT NULL,
  `identify_type` int(11) DEFAULT NULL,
  `points` int(11) DEFAULT '0',
  `points_number` int(11) DEFAULT NULL,
  `level` int(11) DEFAULT NULL,
  `virtual_money` int(11) DEFAULT NULL,
  `agio` double DEFAULT NULL,
  `card_id` varchar(32) DEFAULT NULL,
  `deleted` int(11) DEFAULT '0',
  `is_bind_email` tinyint(1) DEFAULT NULL,
  `is_bind_mobile` int(2) DEFAULT '0',
  `mobile` varchar(16) DEFAULT NULL,
  `is_freeze` int(11) DEFAULT '0',
  `kindergartenid` varchar(32) DEFAULT NULL,
  `schoolid` varchar(32) DEFAULT NULL,
  `junior_schoolid` varchar(32) DEFAULT NULL,
  `senior_schoolid` varchar(32) DEFAULT NULL,
  `remark` varchar(800) DEFAULT NULL,
  `schoolname` varchar(100) DEFAULT NULL,
  `districtid` varchar(32) DEFAULT NULL,
  `source_id` varchar(32) DEFAULT NULL,
  `create_date` timestamp NULL DEFAULT NULL,
  `isactive` int(11) DEFAULT '0',
  `registtype` int(11) DEFAULT '0',
  `hobby` text,
  `describe` text,
  `ty_info_id` varchar(32) DEFAULT NULL,
  `speciality` text,
  `activities` text,
  `create_id` varchar(32) DEFAULT NULL,
  `modify_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modify_id` varchar(32) DEFAULT NULL,
  `drawCard_serviceCenter_id` varchar(32) DEFAULT NULL,
  `regist_class_count` int(11) NOT NULL DEFAULT '0',
  `hebin1` varchar(30) DEFAULT NULL,
  `hebin2` varchar(30) DEFAULT NULL,
  `hebin3` varchar(30) DEFAULT NULL,
  `hebin4` varchar(30) DEFAULT NULL,
  `is_verify` tinyint(1) DEFAULT NULL,
  `create_system` int(10) DEFAULT '1',
  `bind_mobile` varchar(32) DEFAULT NULL,
  `other_schoolname` varchar(100) DEFAULT NULL,
  `other_kindergartenname` varchar(100) DEFAULT NULL,
  `other_juniorschoolname` varchar(100) DEFAULT NULL,
  `other_seniorschoolname` varchar(100) DEFAULT NULL,
  `is_mobi` int(4) DEFAULT '0' COMMENT '屏蔽摩比数据',
  `bi_test` int(11) DEFAULT '0' COMMENT '是否为测试数据0：否；1：是',
  `is_study_abroad` int(11) DEFAULT NULL COMMENT '是否有出国留学意向(0否，1是)',
  `is_diff_college_exam` int(11) DEFAULT NULL COMMENT '是否因户籍问题而在异地参加高考(0否，1是)',
  `father_dept` varchar(100) DEFAULT NULL,
  `mater_dept` varchar(100) DEFAULT NULL,
  `name_spell` varchar(30) DEFAULT NULL,
  `english_name` varchar(30) DEFAULT NULL,
  `student_code` varchar(50) DEFAULT NULL,
  `candidate_serviceCenter_id` varchar(32) DEFAULT NULL,
  `flash_glod` int(11) DEFAULT '0',
  `zk_code` varchar(20) DEFAULT NULL,
  `attendance_card_status` int(15) NOT NULL DEFAULT '0' COMMENT '考勤卡状态(0未绑定 1已绑定 2已挂失 3已作废)',
  `attendance_card_id` varchar(32) DEFAULT NULL COMMENT '考勤卡ID',
  `attendance_card_number` varchar(15) DEFAULT NULL COMMENT '考勤卡编号',
  `attendance_card_model_id` varchar(32) DEFAULT NULL COMMENT '考勤卡型号ID',
  `attendance_card_model` varchar(50) DEFAULT NULL COMMENT '考勤卡型号',
  `attendance_card_style_id` varchar(32) DEFAULT NULL COMMENT '考勤卡类型ID',
  `attendance_card_style` varchar(50) DEFAULT NULL COMMENT '考勤卡类型',
  `first_pay_date` datetime DEFAULT NULL COMMENT '学员第一次缴费时间',
  `first_pay_class_type` tinyint(4) DEFAULT NULL COMMENT '学员第一次报班并缴费的班级类型（0：短期班；1：长期班；）',
  `qqnum` varchar(30) DEFAULT NULL COMMENT 'qq号',
  `weixinnum` varchar(30) DEFAULT NULL COMMENT '微信号',
  `card_modify_date` timestamp NULL DEFAULT NULL,
  `householdregarea` varchar(32) DEFAULT NULL,
  `isschooladvice` int(11) DEFAULT NULL,
  `if_regin_xes_app` int(11) NOT NULL DEFAULT '1' COMMENT '是否注册学而思app',
  `target_schoolid1` varchar(32) DEFAULT NULL COMMENT '目标学校1ID',
  `target_schoolid2` varchar(32) DEFAULT NULL COMMENT '目标学校2ID',
  `target_schoolid3` varchar(32) DEFAULT NULL COMMENT '目标学校3ID',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


