CREATE DATABASE /*!32312 IF NOT EXISTS*/ `udip_target` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_bin */;

USE `udip_target`;

DROP TABLE IF EXISTS `department`;
CREATE TABLE `department` (
  `id`                          VARCHAR(32) NOT NULL,
  `discriminator`               VARCHAR(20)          DEFAULT NULL,
  `name`                        VARCHAR(50)          DEFAULT NULL,
  `parent_id`                   VARCHAR(32)          DEFAULT NULL,
  `is_serv`                     INT(11)              DEFAULT '0',
  `create_date`                 TIMESTAMP   NULL     DEFAULT CURRENT_TIMESTAMP,
  `master`                      VARCHAR(32)          DEFAULT NULL,
  `master_tel`                  VARCHAR(20)          DEFAULT NULL,
  `second_person`               VARCHAR(32)          DEFAULT NULL,
  `second_person_tel`           VARCHAR(20)          DEFAULT NULL,
  `phone`                       VARCHAR(20)          DEFAULT NULL,
  `address`                     VARCHAR(200)         DEFAULT NULL,
  `areaid`                      VARCHAR(32)          DEFAULT NULL,
  `order`                       VARCHAR(30)          DEFAULT NULL,
  `serv_order`                  INT(11)              DEFAULT NULL,
  `terminal_no`                 VARCHAR(50)          DEFAULT NULL
  COMMENT '终端号',
  `code`                        VARCHAR(20)          DEFAULT NULL
  COMMENT '编号',
  `city_id`                     VARCHAR(32)          DEFAULT NULL
  COMMENT '城市',
  `is_show_student`             INT(2)               DEFAULT '0'
  COMMENT '是否在家校平台显示(0：不显示；1：显示；)',
  `is_show_teacher`             INT(2)               DEFAULT '0'
  COMMENT '是否在教师平台显示(0：不显示；1：显示；)',
  `creater_id`                  VARCHAR(32)          DEFAULT NULL,
  `is_receive`                  INT(2)               DEFAULT '0',
  `deleted`                     INT(2)               DEFAULT '0',
  `disable`                     INT(2)               DEFAULT '0',
  `longitude`                   DOUBLE               DEFAULT NULL,
  `latitude`                    DOUBLE               DEFAULT NULL,
  `serv_address`                VARCHAR(500)         DEFAULT NULL,
  `is_call_service_center`      INT(11)              DEFAULT '0',
  `first_char`                  VARCHAR(20)          DEFAULT NULL
  COMMENT '服务中心首字母',
  `district_id`                    VARCHAR(32)          DEFAULT NULL,
  `mobile_alias`                VARCHAR(80)          DEFAULT NULL
  COMMENT 'M站别名',
  `mobile_area_id`              VARCHAR(32)          DEFAULT NULL
  COMMENT '所属M站地区',
  `is_show_in_mobile`           INT(11)              DEFAULT '0'
  COMMENT '是否在M站显示',
  `business_reimbursement_date` TIMESTAMP   NOT NULL DEFAULT '0000-00-00 00:00:00',
  `simple_name`                 VARCHAR(50)          DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_longitude` (`longitude`),
  KEY `index_latitude` (`latitude`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;


DROP TABLE IF EXISTS `teacher`;
CREATE TABLE `teacher` (
  `id` varchar(32) NOT NULL,
  `city_id`              VARCHAR(10)      not NULL DEFAULT '0',
  `teacher_name` varchar(200) DEFAULT NULL,
  `real_name` varchar(20) DEFAULT NULL COMMENT '真实姓名',
  `login_name` varchar(20) DEFAULT NULL,
  `login_pwd` varchar(20) DEFAULT NULL,
  `teacher_code` varchar(20) DEFAULT NULL,
  `identify_num` varchar(20) DEFAULT NULL,
  `sex` int(11) DEFAULT NULL,
  `ismarraied` int(11) DEFAULT NULL,
  `title` varchar(30) DEFAULT NULL,
  `picture_url` varchar(255) DEFAULT NULL,
  `email` varchar(50) DEFAULT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `post` varchar(10) DEFAULT NULL,
  `nation_id` varchar(32) DEFAULT NULL,
  `birthday` date DEFAULT NULL,
  `birthpalce_city_id` varchar(32) DEFAULT NULL,
  `birthpalce` varchar(300) DEFAULT NULL,
  `address_city_id` varchar(32) DEFAULT NULL,
  `address` varchar(300) DEFAULT NULL,
  `graduation_school` varchar(300) DEFAULT NULL,
  `graduation_school_city_id` varchar(32) DEFAULT NULL,
  `school_startdate` date DEFAULT NULL,
  `school_enddate` date DEFAULT NULL,
  `profession` varchar(100) DEFAULT NULL,
  `school_degree` int(4) DEFAULT NULL,
  `originalschoolorganization_name` varchar(100) DEFAULT NULL,
  `nowschoolorganization_name` varchar(100) DEFAULT NULL,
  `organization_startdate` date DEFAULT NULL,
  `organization_enddate` date DEFAULT NULL,
  `old_teach_subject` varchar(50) DEFAULT NULL,
  `old_teach_result` text,
  `old_classfees` varchar(20) DEFAULT NULL,
  `features` text,
  `experience` text,
  `comment` text,
  `teach_result` text,
  `teach_year` date DEFAULT NULL,
  `people_amount_gap_id` varchar(32) DEFAULT NULL,
  `jobtype_id` varchar(32) DEFAULT NULL,
  `joindate` date DEFAULT NULL,
  `contract_type` varchar(32) DEFAULT NULL,
  `contract_area` varchar(32) DEFAULT NULL,
  `subject_id` varchar(32) DEFAULT NULL,
  `resume_id` varchar(32) DEFAULT NULL,
  `wagelevel` varchar(32) DEFAULT NULL,
  `degree_id` varchar(32) DEFAULT NULL,
  `term_type` int(11) DEFAULT NULL,
  `hourfee` varchar(20) DEFAULT NULL,
  `voluntary_hour` varchar(20) DEFAULT NULL,
  `voluntary_gt_id` varchar(32) DEFAULT NULL,
  `deposit` int(4) DEFAULT NULL,
  `awards` int(4) DEFAULT NULL,
  `state` int(11) DEFAULT '0',
  `teacher_cardnumber` varchar(200) DEFAULT NULL,
  `teacher_cardnumber_password` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `teacher_new_pwd` varchar(50) NOT NULL DEFAULT '' COMMENT '教师新登录密码(MD5),旧密码教师重构二期后废弃',
  `teacher_wage_password` varchar(50) DEFAULT NULL,
  `accountlocation` varchar(300) DEFAULT NULL,
  `accountlocation_city_id` varchar(32) DEFAULT NULL,
  `teacher_emergency_contacts` varchar(20) DEFAULT NULL,
  `teacher_emergency_contacts_phone` varchar(20) DEFAULT NULL,
  `teacher_home_phone` varchar(20) DEFAULT NULL,
  `contract_startdate` date DEFAULT NULL,
  `contract_enddate` date DEFAULT NULL,
  `fulltime_appointment_date` date DEFAULT NULL,
  `socialsecurity_payment_date` date DEFAULT NULL,
  `fund_payment_date` date DEFAULT NULL,
  `radix` int(11) DEFAULT NULL,
  `bank_id` varchar(32) DEFAULT NULL,
  `other_bank` varchar(50) DEFAULT NULL,
  `competition_exp` text,
  `original_seniority` int(11) DEFAULT NULL,
  `nowschool_cityzone` varchar(20) DEFAULT NULL,
  `startend_time` varchar(20) DEFAULT NULL,
  `statusquo_complement` text,
  `creater_id` varchar(32) DEFAULT NULL,
  `info_collect_type_id` varchar(32) DEFAULT NULL,
  `isrecommend` int(11) DEFAULT NULL,
  `school_appraise` text,
  `info_content` text,
  `teaching_materials` varchar(100) DEFAULT NULL,
  `teaching_materials_positive` int(11) DEFAULT NULL,
  `scheduling` varchar(100) DEFAULT NULL,
  `scheduling_positive` int(11) DEFAULT NULL,
  `activity_organization` varchar(100) DEFAULT NULL,
  `activity_organization_positive` int(11) DEFAULT NULL,
  `cultivate` varchar(100) DEFAULT NULL,
  `cultivate_positive` int(11) DEFAULT NULL,
  `teacher_care` varchar(100) DEFAULT NULL,
  `teacher_care_positive` int(11) DEFAULT NULL,
  `subject_publicize` varchar(100) DEFAULT NULL,
  `subject_publicize_positive` int(11) DEFAULT NULL,
  `student_manage` varchar(100) DEFAULT NULL,
  `student_manage_positive` int(11) DEFAULT NULL,
  `pay_positive` int(11) DEFAULT NULL,
  `jump_pay_positive` int(11) DEFAULT NULL,
  `Platform_use_positive` int(11) DEFAULT NULL,
  `other_content_type` text,
  `birthday_properties` int(11) DEFAULT NULL,
  `birthday_remarks` varchar(100) DEFAULT NULL,
  `profess_type_id` varchar(32) DEFAULT NULL,
  `profess_department` varchar(50) DEFAULT NULL,
  `source_id` varchar(32) DEFAULT NULL,
  `teaching_point_services_positive` int(11) DEFAULT NULL,
  `appointment_date` date DEFAULT NULL,
  `createdate` date DEFAULT NULL,
  `school_degree_name` varchar(20) DEFAULT NULL,
  `hebin1` varchar(100) DEFAULT NULL,
  `hebin2` varchar(100) DEFAULT NULL,
  `hebin3` varchar(100) DEFAULT NULL,
  `hebin4` varchar(100) DEFAULT NULL,
  `modifydate` date DEFAULT NULL,
  `popularize` int(11) DEFAULT '0',
  `is_web_show` int(11) DEFAULT '0',
  `popularize_date` date DEFAULT NULL,
  `motto` text,
  `introduction` text,
  `login_start` datetime DEFAULT NULL,
  `login_count` int(8) DEFAULT NULL,
  `social_security_radix` int(11) DEFAULT NULL,
  `video_url` text,
  `issign_zk` int(11) DEFAULT '0',
  `issign_wx` int(11) DEFAULT '0',
  `random_password` varchar(10) DEFAULT '0',
  `randpwd_time` datetime DEFAULT NULL,
  `position_type` int(11) NOT NULL DEFAULT '0' COMMENT '教师职位（0普通教师，1班主任）',
  `lesson` int(11) DEFAULT '0',
  `firstChar` varchar(100) DEFAULT NULL,
  `allChar` varchar(100) DEFAULT NULL,
  `classtype` varchar(10) DEFAULT NULL COMMENT '教师所带班型（在数据库中保存以,进行分割）',
  `name_pinyin` varchar(32) DEFAULT NULL,
  `tags` varchar(1000) DEFAULT NULL,
  `app_message_subjects_code` bigint(20) DEFAULT NULL,
  `emp_no` varchar(10) DEFAULT NULL COMMENT '员工编号',
  `double_teacher_state` int(1) DEFAULT NULL COMMENT '是否双师（0否，1是）',
  `common_teacher_state` int(1) DEFAULT NULL COMMENT '是否普通（0否，1是）',
  `live_teacher_state` int(11) DEFAULT '0' COMMENT '是否在线（0不是，1是）',
  `enterprise_email` varchar(50) DEFAULT NULL COMMENT '企业邮箱',
  `positions` varchar(50) DEFAULT NULL COMMENT '教师岗位',
  `create_type` int(1) DEFAULT NULL COMMENT '创建类型（1系统创建，2人工创建）',
  `picture_url_oss` varchar(255) DEFAULT NULL,
  `telephone` varchar(20) DEFAULT NULL COMMENT '主讲个人绑定手机号',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



DROP TABLE IF EXISTS `class_regist_count`;
CREATE TABLE `class_regist_count` (
  `id`           VARCHAR(32) NOT NULL,
  `city_id`              VARCHAR(10)      not NULL DEFAULT '0',
  `id_version`   INT(11)     NOT NULL DEFAULT '0',
  `class_id`     VARCHAR(32)          DEFAULT NULL,
  `regist_count` INT(11)     NOT NULL DEFAULT '0',
  `modify_date`  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `index_class_id` (`class_id`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;


DROP TABLE IF EXISTS `classlevel`;
CREATE TABLE `classlevel` (
  `id`                   VARCHAR(32)  NOT NULL,
  `name`                 VARCHAR(60)           DEFAULT NULL,
  `city_id`              VARCHAR(10)      not NULL DEFAULT '0',
  `order`                INT(11)               DEFAULT '0',
  `display_name`         VARCHAR(60)           DEFAULT NULL,
  `degree`               DOUBLE(4, 2) NOT NULL,
  `parent_id`            VARCHAR(32)           DEFAULT '0',
  `type`                 INT(11)               DEFAULT '0',
  `deleted`              INT(11)               DEFAULT '0',
  `create_date`          TIMESTAMP    NULL     DEFAULT CURRENT_TIMESTAMP,
  `creater_id`           VARCHAR(32)           DEFAULT NULL,
  `modify_date`          TIMESTAMP    NULL     DEFAULT NULL,
  `modify_id`            VARCHAR(32)           DEFAULT NULL,
  `status`               INT(11)               DEFAULT '0',
  `is_leaf`              INT(11)      NOT NULL DEFAULT '1',
  `term_is_show_student` INT(11)               DEFAULT '0',
  `term_is_show_teacher` INT(11)               DEFAULT '0',
  `is_mobi`              INT(4)                DEFAULT '0'
  COMMENT '屏蔽摩比数据',
  `is_live_lesson`       INT(11)               DEFAULT '0',
  `disable`              INT(11)               DEFAULT '0'
  COMMENT '状态：0-可用，1-停用',
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS `classtime`;
CREATE TABLE `classtime` (
  `id` varchar(32) NOT NULL,
  `city_id`              VARCHAR(10)      not NULL DEFAULT '0',
  `type_id` varchar(32) DEFAULT NULL,
  `time_name` varchar(200) DEFAULT NULL,
  `start_time` time DEFAULT NULL,
  `end_time` time DEFAULT NULL,
  `class_hours` double DEFAULT NULL,
  `is_show_teacher` int(11) DEFAULT '0',
  `order` int(11) DEFAULT NULL,
  `deleted` int(11) DEFAULT '0',
  `create_id` varchar(32) DEFAULT NULL,
  `create_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_id` varchar(32) DEFAULT NULL,
  `modify_date` datetime DEFAULT NULL,
  `period` varchar(20) DEFAULT NULL COMMENT '时段(上午,下午,晚上)',
  `period_type` int(11) DEFAULT NULL COMMENT '时段类型(1：上午,2：下午,3：晚上)',
  `status` int(11) DEFAULT '0' COMMENT ' 0 正常；1 停用',
  PRIMARY KEY (`id`),
  KEY `index_type_id` (`type_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



DROP TABLE IF EXISTS `classtime_type`;
CREATE TABLE `classtime_type` (
  `id`                   VARCHAR(32) NOT NULL,
  `name`                 VARCHAR(30)      DEFAULT NULL,
  `city_id`              VARCHAR(10)      not NULL DEFAULT '0',
  `order`                INT(11)          DEFAULT NULL,
  `deleted`              INT(11)          DEFAULT '0',
  `create_id`            VARCHAR(32)      DEFAULT NULL,
  `create_date`          TIMESTAMP   NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_id`            VARCHAR(32)      DEFAULT NULL,
  `modify_date`          TIMESTAMP   NULL DEFAULT NULL,
  `timeType_classifyInt` VARCHAR(50)      DEFAULT NULL
  COMMENT '时间类别',
  `timeType_classify`    VARCHAR(100)     DEFAULT NULL
  COMMENT '时间类别',
  `className_use`        INT(11)          DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;


DROP TABLE IF EXISTS `change_course_amount`;
CREATE TABLE `change_course_amount` (
  `id` varchar(32) NOT NULL COMMENT 'id',
  `city_id` varchar(32)  NULL,
  `class_type` int(11) DEFAULT NULL COMMENT '授课类型',
  `grade_type_id` varchar(32) DEFAULT NULL COMMENT '年部id',
  `grade_type_name` varchar(50) DEFAULT NULL COMMENT '年部名称',
  `grade_id` varchar(32) DEFAULT NULL COMMENT '年级id',
  `grade_name` varchar(50) DEFAULT NULL COMMENT '年级名称',
  `change_course_amount` int(11) DEFAULT NULL COMMENT '可多调人数限额',
  `isdeleted` int(11) DEFAULT '0' COMMENT '是否删除',
  `creater_id` varchar(32) DEFAULT NULL COMMENT '创建人',
  `creater_name` varchar(50) DEFAULT NULL COMMENT '创建人姓名',
  `create_date` datetime DEFAULT NULL COMMENT '创建时间',
  `modifier_id` varchar(32) DEFAULT NULL COMMENT '修改人',
  `modifier_name` varchar(50) DEFAULT NULL COMMENT '修改人姓名',
  `modify_date` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `system_param`;
CREATE TABLE `system_param` (
  `id` varchar(32) NOT NULL,
  `city_id` varchar(32)  NULL,
  `param_name` varchar(100) DEFAULT NULL,
  `param_alias` varchar(100) DEFAULT NULL,
  `param_value` varchar(100) DEFAULT NULL,
  `deleted` int(11) DEFAULT '0',
  `creater_id` varchar(32) DEFAULT NULL,
  `create_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `version` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_param_alias` (`param_alias`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `district`;
CREATE TABLE `district` (
  `id` varchar(32) NOT NULL,
  `name` varchar(50) DEFAULT NULL,
  `description` varchar(500) DEFAULT NULL,
  `link_url` varchar(200) DEFAULT NULL,
  `order` int(11) DEFAULT NULL,
  `code` varchar(4) DEFAULT NULL,
  `city_id` varchar(32) DEFAULT NULL,
  `deleted` int(11) DEFAULT '0',
  `creater_id` varchar(32) DEFAULT NULL,
  `create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `curriculum`;
CREATE TABLE `curriculum` (
  `id` varchar(32) NOT NULL COMMENT '主键ID',
  `class_id` varchar(32) DEFAULT NULL COMMENT '班级ID',
  `class_num` int(11) DEFAULT NULL COMMENT '课次号',
  `class_date` date DEFAULT NULL COMMENT '上课日期 yyyy-MM-dd',
  `classtime_id` varchar(32) DEFAULT NULL COMMENT '上课时间ID',
  `start_time` time DEFAULT NULL COMMENT '上课时间 HH:mm:ss',
  `end_time` time DEFAULT NULL COMMENT '下课时间 HH:mm:ss',
  `teacher_id` varchar(32) DEFAULT NULL COMMENT '主键老师ID',
  `subject_id` varchar(32) DEFAULT NULL COMMENT '学科ID',
  `teacher_type` int(11) DEFAULT NULL COMMENT '教师类型（0：正常上课，1：代课）',
  `classroom_id` varchar(32) DEFAULT NULL COMMENT '教室ID',
  `is_delete` int(11) DEFAULT '0' COMMENT '是否已删除（0：否，1：是）',
  `status` int(11) DEFAULT '0' COMMENT '状态（0：未上课，1：已上课）',
  `is_attendance` int(11) DEFAULT NULL COMMENT '考勤（0：未考勤，1：已考勤）',
  `changein_course_num` int(11) NOT NULL DEFAULT '0' COMMENT '调入人数',
  `changeout_course_num` int(11) NOT NULL DEFAULT '0' COMMENT '调出人数',
  `version` int(11) DEFAULT '0' COMMENT '版本号',
  `lock_status` int(11) DEFAULT '0' COMMENT '锁定状态（0：未锁定，1：已锁定，2：已解锁）',
  `cancel` int(11) NOT NULL DEFAULT '0' COMMENT '是否取消（0：否，1：是）',
  `print_date` datetime DEFAULT NULL COMMENT '打印时间',
  `is_test` int(11) DEFAULT '0' COMMENT '是否是测试数据（0：否，1：是）',
  `classtime_type_id` varchar(32) DEFAULT NULL COMMENT '上课时间类型id',
  `classtime_name` varchar(50) DEFAULT NULL COMMENT '上课时间名称',
  `name` varchar(100) DEFAULT NULL COMMENT '课次名称',
  `tutor_id` varchar(100) DEFAULT NULL COMMENT '辅导老师ID',
  `tutor_real_name` varchar(100) DEFAULT NULL COMMENT '辅导老师名称',
  `is_allow_tutor_conflict` int(2) DEFAULT '0' COMMENT '辅导老师是否允许冲突（0：否，1：是）',
  `is_allow_classroom_conflict` int(2) DEFAULT '0' COMMENT '教室是否允许冲突（0：否，1：是）',
  `city_id` varchar(10) NOT NULL COMMENT '分校ID，如：010',
  `modify_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `clazz`;
CREATE TABLE `clazz` (
  `id` varchar(32) NOT NULL COMMENT '主键ID',
  `name` varchar(200) DEFAULT NULL COMMENT '班级名称',
  `year` varchar(4) DEFAULT NULL COMMENT '年份',
  `term_id` varchar(32) DEFAULT NULL COMMENT '学期ID',
  `term_name` varchar(50) DEFAULT NULL COMMENT '学期名称',
  `grade_id` varchar(32) DEFAULT NULL COMMENT '年级ID',
  `grade_name` varchar(32) DEFAULT NULL COMMENT '年级名称',
  `grade_type_id` varchar(32) DEFAULT NULL COMMENT '年级类型ID',
  `grade_type_name` varchar(50) DEFAULT NULL COMMENT '年级类型名称',
  `subject_ids` varchar(400) DEFAULT NULL COMMENT '学科ID(多个逗号隔开)',
  `subject_names` varchar(300) DEFAULT NULL COMMENT '学科名称(多个逗号隔开)',
  `subject_long_value` bigint(20) DEFAULT NULL COMMENT '学科(Long值)',
  `level_id` varchar(32) DEFAULT NULL COMMENT '班次ID',
  `level_name` varchar(300) DEFAULT NULL COMMENT '班次名称',
  `attend_statistics_type_id` varchar(32) DEFAULT NULL COMMENT '考勤统计类别ID',
  `attend_statistics_type_name` varchar(128) DEFAULT NULL COMMENT '考勤统计类别名称',
  `area_id` varchar(32) DEFAULT NULL COMMENT '地区ID（商圈）',
  `area_name` varchar(50) DEFAULT NULL COMMENT '地区名称（商圈）',
  `servicecenter_id` varchar(32) DEFAULT NULL COMMENT '服务中心ID',
  `servicecenter_name` varchar(200) DEFAULT NULL COMMENT '服务中心名称',
  `servicecenter_address` varchar(200) DEFAULT NULL COMMENT '服务中心地址',
  `venue_id` varchar(32) DEFAULT NULL COMMENT '教学点ID',
  `venue_name` varchar(200) DEFAULT NULL COMMENT '教学点名称',
  `classroom_id` varchar(32) DEFAULT NULL COMMENT '教室ID',
  `classroom_name` varchar(200) DEFAULT NULL COMMENT '教室名称',
  `template_id` varchar(32) DEFAULT NULL COMMENT '班级模板ID',
  `source_class_id` varchar(500) DEFAULT NULL COMMENT '续报原班ID（多个逗号隔开）',
  `start_date` date DEFAULT NULL COMMENT '开课日期',
  `end_date` date DEFAULT NULL COMMENT '结课日期',
  `classdate_id` varchar(32) DEFAULT NULL COMMENT '上课日期ID',
  `classdate_name` varchar(100) DEFAULT NULL COMMENT '上课日期名称',
  `classtime_ids` varchar(1000) DEFAULT NULL COMMENT '上课时间ID（多个逗号隔开）',
  `classtime_names` varchar(1000) DEFAULT NULL COMMENT '上课时间名称（多个逗号隔开）',
  `frequency` int(11) DEFAULT NULL COMMENT '上课频率（单位：天）',
  `exclude_date` varchar(2000) DEFAULT NULL COMMENT '排除日期',
  `every_hours` double DEFAULT NULL COMMENT '每次课课时数',
  `classtime_type_id` varchar(1000) DEFAULT NULL COMMENT '格式：上课时间类型ID  +  | + 上课时间id',
  `classtime_time_period` varchar(20) DEFAULT NULL COMMENT '上课时间段，如：上午、中午、下午、晚上',
  `classtime_time_classify` varchar(100) DEFAULT NULL COMMENT '格式：周一------周日，一期-----六期',
  `teacher_ids` varchar(1000) DEFAULT NULL COMMENT '主讲老师ID（多个逗号隔开）',
  `teacher_names` varchar(1000) DEFAULT NULL COMMENT '主讲老师名称（多个逗号隔开）',
  `teacher_codes` varchar(100) DEFAULT NULL COMMENT '教师编号',
  `class_teacher_id` varchar(32) DEFAULT NULL COMMENT '班主任ID',
  `class_teacher_name` varchar(20) DEFAULT NULL COMMENT '班主任名称',
  `tutor_id` varchar(32) DEFAULT NULL COMMENT '辅导老师ID',
  `tutor_real_name` varchar(200) DEFAULT NULL COMMENT '辅导老师名称',
  `class_count` int(11) DEFAULT NULL COMMENT '总课次数',
  `passed_count` int(11) DEFAULT NULL COMMENT '通过课次数',
  `price` double DEFAULT NULL COMMENT '课程总金额',
  `max_persons` int(11) DEFAULT NULL COMMENT '班级最大人数',
  `add_max_persons` int(11) DEFAULT '0' COMMENT '超限额人数',
  `add_max_start_date` date DEFAULT NULL COMMENT '超限额生效日期',
  `add_max_end_date` date DEFAULT NULL COMMENT '超限额失效日期',
  `exam_id` varchar(32) DEFAULT NULL COMMENT '考试ID',
  `status` int(11) DEFAULT NULL COMMENT '状态（0：未确认，1：已确认，2：已发布）',
  `audit_status` int(11) DEFAULT '1' COMMENT '班级审核状态（1：开班未审核，2：开班已审核，3：变动未审核，4：变动已审核，5：变动驳回）',
  `auditor_id` varchar(32) DEFAULT NULL COMMENT '审核人ID',
  `audit_date` datetime DEFAULT NULL COMMENT '审核时间',
  `feetype` int(11) DEFAULT NULL COMMENT '收费类型（1：不收报名费，2：收报名费）',
  `pay_end_date` datetime DEFAULT NULL COMMENT '缴费截止日期',
  `class_introduction` varchar(300) DEFAULT NULL COMMENT '班级介绍',
  `class_introduction_modifier` varchar(50) DEFAULT NULL COMMENT '班级介绍修改人',
  `class_introduction_modified_time` datetime DEFAULT NULL COMMENT '班级介绍修改时间',
  `curriculum_lock_status` int(11) DEFAULT '0' COMMENT '课表锁定状态（0：未锁定，1：已锁定，2：已解锁）',
  `lock_log_id` varchar(32) DEFAULT NULL COMMENT '课表锁定、解锁日志ID',
  `recommend_number` varchar(350) DEFAULT NULL COMMENT '推荐课程编号',
  `recommend_number_MD5` varchar(350) DEFAULT NULL COMMENT '推荐课编号MD5值 (年份 学期 年级 推荐班编号 生成)',
  `is_allow_teacher_conflict` int(1) DEFAULT '0' COMMENT '是否允许教师冲突(0：不允许，1：允许)',
  `is_allow_classroom_conflict` int(1) DEFAULT '0' COMMENT '是否允许教室冲突(0：不允许，1：允许)',
  `is_schooltest` int(11) DEFAULT '1' COMMENT '是否需要入学测试（0：否，1：是）',
  `is_test` int(11) DEFAULT '0' COMMENT '是否测试数据（0：否，1：是）',
  `is_attend` int(11) DEFAULT '0' COMMENT '是否允许旁听（0：否，1：是）',
  `is_display_front` int(11) DEFAULT NULL COMMENT '前台是否显示（0：否，1：是）',
  `is_display_teacher` int(11) DEFAULT NULL COMMENT '教师系统是否显示（0：否，1：是）',
  `is_display_student` int(11) DEFAULT NULL COMMENT '家校是否显示（0：否，1：是）',
  `is_delete` int(11) DEFAULT '0' COMMENT '是否已删除（0：否，1：是）',
  `is_close` int(11) DEFAULT '0' COMMENT '是否已关闭（0：否，1：是）',
  `is_expired` int(11) DEFAULT '0' COMMENT '是否已过期（0：否，1：是；过期班级续报率不统计）',
  `is_recommend` int(11) DEFAULT NULL COMMENT '是否热推（0：否，1：是）',
  `is_hidden` int(11) DEFAULT '1' COMMENT '是否隐藏（0：否，1：是）',
  `is_pay` int(11) DEFAULT '0' COMMENT '是否允许网上缴费（0：否，1：是）',
  `is_fee` int(4) DEFAULT '1' COMMENT '是否收费(0：否，1：是)',
  `is_collection_charges` int(4) DEFAULT '0' COMMENT '是否代收费(0：否；1：是)',
  `is_statistic` int(11) DEFAULT NULL COMMENT '是否计入学而思统计（0：否，1：是）',
  `is_beili_build` int(11) DEFAULT '0' COMMENT '在线外教排课是否完成（0：否，1：是）（预计可删除）',
  `is_beili` int(11) DEFAULT '0' COMMENT '是否是在线外教（0：否，1：是）（预计可删除）',
  `is_web_regist` int(11) DEFAULT '1' COMMENT '是否允许培优网报名（0：不允许，1：允许）',
  `is_push_to_xes_im` int(4) NOT NULL DEFAULT '0' COMMENT '是否已推送给XesIM（0：否，1：是）',
  `is_live_class` int(1) DEFAULT '1' COMMENT '是否是直播班（0：否，1：是）',
  `is_double_teacher_live_class` int(1) DEFAULT '0' COMMENT '是否双师直播班(0：否，1：是)',
  `live_number_id` varchar(32) DEFAULT NULL COMMENT '直播班编号',
  `live_class_template_id` varchar(32) DEFAULT NULL COMMENT '直播班级模板ID',
  `live_class_time_id` varchar(32) DEFAULT NULL COMMENT '直播时间段ID',
  `live_class_type` int(1) DEFAULT NULL COMMENT '直播类型 (0:直播  1：录播)',
  `class_type` int(2) DEFAULT NULL COMMENT '授课类型（1：在线，2：双师，4：面授，8：线上班）',
  `nickname` varchar(30) DEFAULT NULL COMMENT '班级别称',
  `admin_status` int(1) DEFAULT NULL COMMENT '是否设定管理员（0：不设置，1：设置；海边使用）',
  `course_id` varchar(32) DEFAULT NULL COMMENT '课程ID',
  `courseware_send` int(2) DEFAULT '2' COMMENT '课程材料寄送（1：寄送，2：不寄送；默认：2）',
  `headquarters_openclass` int(2) DEFAULT '1' COMMENT '是否需要总部开班（0：不需要，1：需要；默认：1）',
  `biz_type` int(11) DEFAULT '0' COMMENT '课程业务类型（0：普通课程，1：第二课堂，2：学而思国际；默认：0）',
  `create_type` int(11) DEFAULT NULL COMMENT '班级数据创建方式（1：模板开班，2：非模板开班，3：面授导班，4：课程开班，5：课程导班，6：批量课程导班，7：班级修改）',
  `create_date` datetime DEFAULT NULL COMMENT '创建时间（yyyy-MM-dd HH:mm:ss）',
  `creater_id` varchar(32) DEFAULT NULL COMMENT '创建人ID',
  `version` int(11) DEFAULT '0' COMMENT '版本号',
  `modify_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间（yyyy-MM-dd HH:mm:ss）',
  `modify_id` varchar(32) DEFAULT NULL COMMENT '更人人ID',
  `class_change_id` varchar(32) DEFAULT NULL COMMENT '班级变动记录ID',
  `class_change_name` text COMMENT '班级变动内容',
  `city_id` varchar(10) NOT NULL COMMENT '分校ID，如：010',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

