CREATE DATABASE /*!32312 IF NOT EXISTS*/ `udip_check` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_bin */;

USE `udip_check`;


drop  table  IF EXISTS check_table_rel;
CREATE TABLE `check_table_rel` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TABLE_NAME` varchar(100) DEFAULT NULL COMMENT '表名称',
  `TIME_FIELD_NAME` varchar(100) DEFAULT NULL COMMENT '表对应的时间字段名',
  `KEY_NAME` varchar(100) DEFAULT NULL COMMENT '主键名称',
  `WHERE_SQL` varchar(300) DEFAULT '' COMMENT '数据检查对比时个性化查询条件。以逻辑连接符开始，如，and xxx=aaa',
  `IS_USE` int(11) DEFAULT '0' COMMENT '是否使用，0:使用，1：不能使用',
  `CREATE_DATE` datetime DEFAULT NULL COMMENT '创建时间',
  `UPDATE_DATE` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `TABLE_NAME` (`TABLE_NAME`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8 COMMENT='数据核对表映射信息';


drop  table  IF EXISTS check_data_info;
CREATE TABLE `check_data_info` (
  `ID` bigint(11) NOT NULL AUTO_INCREMENT,
  `CHANNEL_ID` int(11) DEFAULT NULL COMMENT 'channelId',
  `PIPELINE_ID` int(11) DEFAULT NULL COMMENT '管道ID',
  `CHECK_SOURCE_NAME` varchar(50) DEFAULT NULL COMMENT '源数据源名称',
  `CHECK_SOURCE_SCHEMA` varchar(100) DEFAULT NULL COMMENT '源数据库名称',
  `CHECK_SOURCE_TABLE` varchar(100) DEFAULT NULL COMMENT '源表表名称',
  `CHECK_TARGET_NAME` varchar(50) DEFAULT NULL COMMENT '目标数据源名称',
  `CHECK_TARGET_SCHEMA` varchar(100) DEFAULT NULL COMMENT '目标数据库名称',
  `CHECK_TARGET_TABLE` varchar(100) DEFAULT NULL COMMENT '目标表名称',
  `CHECK_BEGIN_DATE` datetime DEFAULT NULL COMMENT '检查开始时间',
  `CHECK_END_DATE` datetime DEFAULT NULL COMMENT '检查结束时间',
  `REPAIR_FAIL_NUM` int(11) DEFAULT '0' COMMENT '修复失败次数',
  `IS_START` int(11) DEFAULT '0' COMMENT '是否启动，0：启动，1：关闭',
  `CREATE_DATE` datetime DEFAULT NULL COMMENT '创建时间',
  `UPDATE_DATE` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=155 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='数据检查';


drop  table  IF EXISTS check_repair_log;
CREATE TABLE `check_repair_log` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `CHANNEL_ID` int(11) DEFAULT NULL COMMENT 'channelId',
  `PIPELINE_ID` int(11) DEFAULT NULL COMMENT '管道ID',
  `CHECK_SOURCE_NAME` varchar(50) DEFAULT NULL COMMENT '源数据源名称',
  `CHECK_SOURCE_SCHEMA` varchar(100) DEFAULT NULL COMMENT '源数据库名称',
  `CHECK_SOURCE_TABLE` varchar(100) DEFAULT NULL COMMENT '源表表名称',
  `CHECK_TARGET_NAME` varchar(50) DEFAULT NULL COMMENT '目标数据源名称',
  `CHECK_TARGET_SCHEMA` varchar(100) DEFAULT NULL COMMENT '目标数据库名称',
  `CHECK_TARGET_TABLE` varchar(100) DEFAULT NULL COMMENT '目标表名称',
  `REPAIR_BEGIN_DATE` datetime DEFAULT NULL COMMENT '修复数据的开始时间',
  `REPAIR_END_DATE` datetime DEFAULT NULL COMMENT '修复数据的结束时间',
  `REPAIR_NUM` int(11) DEFAULT NULL COMMENT '第几次修复',
  `REPAIR_IS_SUCCESS` int(11) DEFAULT NULL COMMENT '是否修复成功，0：成功，1：失败',
  `CREATE_DATE` datetime DEFAULT NULL,
  `UPDATE_DATE` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=72 DEFAULT CHARSET=utf8 COMMENT='数据修复日志';


